setting:
  hostname: localhost
  server:
    - name: main
      subdomain:
        - ~
        - www
        - main
      route: route.yml
    - name: admin
      subdomain:
        - admin
      route: admin.yml
      auth: true
    - name: create
      subdomain:
        - create
      route: create.yml
